### ISSUE TITLE
User Hives

### ISSUE THREAD

**Issue by rtocode** [p0w3rsh3ll/AutoRuns#4]
Hey, awesome tool! Do you plan on supporting the loading and enumerating of user hives?

**Comment by p0w3rsh3ll** [comment]
Hi,
Thank you :-)
Yes I have a plan. 
It's listed in the Todo list [https://github.com/p0w3rsh3ll/AutoRuns/blob/master/TODO.md](https://github.com/p0w3rsh3ll/AutoRuns/blob/master/TODO.md)

**Comment by p0w3rsh3ll** [comment]
@rtocode fyi, the following commit aec5a7dbf343e5aa565fd5a2092c0d46c8ccf783 adds enumeration of loaded hives... see https://github.com/p0w3rsh3ll/AutoRuns/releases/tag/v13.90.1
